// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4XAcYyXv64jJBNetrTMMRi7r_v1CD960',
    appId: '1:637292459031:web:fd1e89fbfee4f0f854d852',
    messagingSenderId: '637292459031',
    projectId: 'messager-49061',
    authDomain: 'messager-49061.firebaseapp.com',
    storageBucket: 'messager-49061.firebasestorage.app',
    measurementId: 'G-2460V6M2FV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVYj7Fk4xSMiL0vR6oxN4m9MenkghjQJs',
    appId: '1:637292459031:android:41a7e8b1f7ccaf4e54d852',
    messagingSenderId: '637292459031',
    projectId: 'messager-49061',
    storageBucket: 'messager-49061.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH_LRlKt3kHQLzKXKaf7__XEJMM7i5rtU',
    appId: '1:637292459031:ios:7cd542fd6179e4da54d852',
    messagingSenderId: '637292459031',
    projectId: 'messager-49061',
    storageBucket: 'messager-49061.firebasestorage.app',
    iosBundleId: 'com.example.transfer',
  );

}